# =============================================================================
# CRA Composite Action: Vulnerability Scan
# =============================================================================
# Multi-engine vulnerability scan using Trivy (primary), Grype and OSV-Scanner.
# Uses official GitHub Actions for all scan engines:
#   - aquasecurity/trivy-action (Trivy)
#   - anchore/scan-action (Grype)
#   - google/osv-scanner-action (OSV-Scanner)
#
# Supports filesystem, container image, and SBOM-based scanning.
# Produces JSON report, SARIF (GitHub Security tab), and severity summary.
#
# Usage:
#   - uses: bauer-group/SEC-CRACompliance/.github/actions/cra-vulnerability-scan@main
#     with:
#       scan-target: '.'
#       fail-on-critical: 'true'
#
# CRA Reference: Art. 10 Abs. 6, Annex I Teil II Nr. 2
# =============================================================================

name: 'ðŸ›¡ï¸ CRA Vulnerability Scan'
description: 'Multi-engine vulnerability scan for CRA compliance (Art. 10 Abs. 6)'

inputs:
  scan-target:
    description: 'Target to scan: directory, image reference, or SBOM file path'
    required: false
    default: '.'
  scan-type:
    description: 'Scan type: fs, image, sbom, auto'
    required: false
    default: 'auto'
  severity-threshold:
    description: 'Minimum severity to report: UNKNOWN, LOW, MEDIUM, HIGH, CRITICAL'
    required: false
    default: 'MEDIUM'
  fail-on-critical:
    description: 'Fail the action if CRITICAL vulnerabilities are found'
    required: false
    default: 'false'
  output-file:
    description: 'Output filename for the scan results'
    required: false
    default: 'vulnerability-report.json'
  enable-grype:
    description: 'Also run Grype as additional scan engine'
    required: false
    default: 'false'
  enable-osv:
    description: 'Run OSV-Scanner as additional scan engine'
    required: false
    default: 'true'
  trivy-version:
    description: 'Trivy version to use'
    required: false
    default: 'latest'

outputs:
  report-path:
    description: 'Path to the Trivy vulnerability report (JSON)'
    value: ${{ github.workspace }}/${{ inputs.output-file }}
  sarif-path:
    description: 'Path to the SARIF report (for GitHub Security tab)'
    value: ${{ github.workspace }}/trivy-results.sarif
  grype-report-path:
    description: 'Path to the Grype vulnerability report (if enabled)'
    value: ${{ steps.grype-scan.outputs.json }}
  osv-report-path:
    description: 'Path to the OSV-Scanner vulnerability report (if enabled)'
    value: ${{ github.workspace }}/osv-scanner-results.sarif
  critical-count:
    description: 'Number of CRITICAL vulnerabilities'
    value: ${{ steps.summary.outputs.critical-count }}
  high-count:
    description: 'Number of HIGH vulnerabilities'
    value: ${{ steps.summary.outputs.high-count }}
  total-count:
    description: 'Total number of vulnerabilities found'
    value: ${{ steps.summary.outputs.total-count }}

runs:
  using: 'composite'
  steps:
    # ---- Detection ----

    - name: ðŸ” Detect scan type
      id: detect
      shell: bash
      run: |
        TARGET="${{ inputs.scan-target }}"
        SCAN_TYPE="${{ inputs.scan-type }}"

        if [ "$SCAN_TYPE" = "auto" ]; then
          if echo "$TARGET" | grep -qE ':|@'; then
            SCAN_TYPE="image"
          elif echo "$TARGET" | grep -qiE '\.cdx\.json$|\.spdx\.json$|sbom.*\.json$'; then
            SCAN_TYPE="sbom"
          else
            SCAN_TYPE="fs"
          fi
        fi

        echo "scan-type=${SCAN_TYPE}" >> "$GITHUB_OUTPUT"

        # Map target to trivy-action input parameters
        if [ "$SCAN_TYPE" = "image" ]; then
          echo "trivy-image-ref=${TARGET}" >> "$GITHUB_OUTPUT"
        elif [ "$SCAN_TYPE" = "sbom" ]; then
          echo "trivy-input=${TARGET}" >> "$GITHUB_OUTPUT"
        else
          echo "trivy-scan-ref=${TARGET}" >> "$GITHUB_OUTPUT"
        fi

    # ---- Trivy Scan ----

    - name: ðŸ›¡ï¸ Run Trivy scan (JSON)
      uses: aquasecurity/trivy-action@0.33.1
      with:
        scan-type: ${{ steps.detect.outputs.scan-type }}
        scan-ref: ${{ steps.detect.outputs.trivy-scan-ref }}
        image-ref: ${{ steps.detect.outputs.trivy-image-ref }}
        input: ${{ steps.detect.outputs.trivy-input }}
        format: 'json'
        output: ${{ inputs.output-file }}
        severity: '${{ inputs.severity-threshold }},HIGH,CRITICAL'
        version: ${{ inputs.trivy-version }}

    - name: ðŸ›¡ï¸ Run Trivy scan (SARIF)
      uses: aquasecurity/trivy-action@0.33.1
      with:
        scan-type: ${{ steps.detect.outputs.scan-type }}
        scan-ref: ${{ steps.detect.outputs.trivy-scan-ref }}
        image-ref: ${{ steps.detect.outputs.trivy-image-ref }}
        input: ${{ steps.detect.outputs.trivy-input }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: '${{ inputs.severity-threshold }},HIGH,CRITICAL'
        version: ${{ inputs.trivy-version }}

    # ---- Grype Scan (optional) ----

    - name: ðŸ›¡ï¸ Run Grype scan
      id: grype-scan
      if: inputs.enable-grype == 'true'
      uses: anchore/scan-action@v7
      with:
        path: ${{ steps.detect.outputs.scan-type == 'fs' && inputs.scan-target || '' }}
        image: ${{ steps.detect.outputs.scan-type == 'image' && inputs.scan-target || '' }}
        sbom: ${{ steps.detect.outputs.scan-type == 'sbom' && inputs.scan-target || '' }}
        output-format: 'json'
        fail-build: false

    # ---- OSV-Scanner (optional) ----

    - name: ðŸ”Ž Run OSV-Scanner (filesystem)
      if: inputs.enable-osv == 'true' && steps.detect.outputs.scan-type == 'fs'
      uses: google/osv-scanner-action@v2.3.2
      with:
        scan-args: |-
          --recursive
          ${{ inputs.scan-target }}
        results-file-name: 'osv-scanner-results.sarif'
        upload-sarif: false
        fail-on-vuln: false
      continue-on-error: true

    - name: ðŸ”Ž Run OSV-Scanner (SBOM)
      if: inputs.enable-osv == 'true' && steps.detect.outputs.scan-type == 'sbom'
      uses: google/osv-scanner-action@v2.3.2
      with:
        scan-args: |-
          --sbom
          ${{ inputs.scan-target }}
        results-file-name: 'osv-scanner-results.sarif'
        upload-sarif: false
        fail-on-vuln: false
      continue-on-error: true

    # ---- Summary ----

    - name: ðŸ“Š Generate summary
      id: summary
      shell: bash
      run: |
        REPORT_PATH="${GITHUB_WORKSPACE}/${{ inputs.output-file }}"

        if command -v jq &>/dev/null && [ -f "$REPORT_PATH" ]; then
          CRITICAL=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' "$REPORT_PATH" 2>/dev/null || echo "0")
          HIGH=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' "$REPORT_PATH" 2>/dev/null || echo "0")
          TOTAL=$(jq '[.Results[]?.Vulnerabilities[]?] | length' "$REPORT_PATH" 2>/dev/null || echo "0")
        else
          CRITICAL=0
          HIGH=0
          TOTAL=0
        fi

        echo "critical-count=${CRITICAL}" >> "$GITHUB_OUTPUT"
        echo "high-count=${HIGH}" >> "$GITHUB_OUTPUT"
        echo "total-count=${TOTAL}" >> "$GITHUB_OUTPUT"

        # OSV-Scanner results (SARIF format)
        OSV_SARIF="${GITHUB_WORKSPACE}/osv-scanner-results.sarif"
        if [ -f "$OSV_SARIF" ] && command -v jq &>/dev/null; then
          OSV_COUNT=$(jq '[.runs[]?.results[]?] | length' "$OSV_SARIF" 2>/dev/null || echo "0")
        else
          OSV_COUNT="skipped"
        fi

        echo "### ðŸ›¡ï¸ Vulnerability Scan Summary" >> "$GITHUB_STEP_SUMMARY"
        echo "| Engine | Severity | Count |" >> "$GITHUB_STEP_SUMMARY"
        echo "|--------|----------|------:|" >> "$GITHUB_STEP_SUMMARY"
        echo "| Trivy | CRITICAL | ${CRITICAL} |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Trivy | HIGH | ${HIGH} |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Trivy | Total | ${TOTAL} |" >> "$GITHUB_STEP_SUMMARY"
        echo "| OSV-Scanner | Total | ${OSV_COUNT} |" >> "$GITHUB_STEP_SUMMARY"

        if [ "${{ inputs.fail-on-critical }}" = "true" ] && [ "$CRITICAL" -gt 0 ]; then
          echo "::error::${CRITICAL} CRITICAL vulnerabilities found"
          exit 1
        fi
